name: CI

on:
  - pull_request
  - push

jobs:
  run:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
    
    - name: Install Dependencies
      run: composer install --prefer-dist
    
    - name: Run tests
      run: vendor/bin/phpunit
